System:
  #FTS_DATABASE_TYPE: SQLite
  FTS_CONNECTION_MESSAGE: Welcome to FreeTAKServer {MainConfig.version}. The Parrot is not dead. It’s just resting
  FTS_SECRET_KEY: vnkdjnfjknfl1232#
  #FTS_OPTIMIZE_API: True
  #FTS_MAINLOOP_DELAY: 1
Addresses:
  FTS_COT_PORT: 8087
  FTS_SSLCOT_PORT: 8089
  FTS_DP_ADDRESS: 0.0.0.0
  FTS_USER_ADDRESS: 0.0.0.0
  FTS_API_PORT: 19023
  FTS_FED_PORT: 9000
  FTS_API_ADDRESS: 0.0.0.0
FileSystem:
  FTS_DB_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\FreeTAKServer.db'
  FTS_COT_TO_DB: True
  FTS_MAINPATH: '</text>Lib\\site-packages\\FreeTAKServer'
  FTS_CERTS_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\certs'
  FTS_EXCHECK_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\ExCheck'
  FTS_EXCHECK_TEMPLATE_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\ExCheck\\template'
  FTS_EXCHECK_CHECKLIST_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\ExCheck\\checklist'
  FTS_DATAPACKAGE_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\FreeTAKServerDataPackageFolder'
  FTS_LOGFILE_PATH: '</text>Lib\\site-packages\\FreeTAKServer\\Logs'
Certs:
  FTS_SERVER_KEYDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.key'
  FTS_SERVER_PEMDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.pem'
  FTS_TESTCLIENT_PEMDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\Client.pem'
  FTS_TESTCLIENT_KEYDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\Client.key'
  FTS_UNENCRYPTED_KEYDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.key.unencrypted'
  FTS_SERVER_P12DIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.p12'
  FTS_CADIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\ca.pem'
  FTS_CAKEYDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\ca.key'
  FTS_FEDERATION_CERTDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.pem'
  FTS_FEDERATION_KEYDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\server.key'
  FTS_CRLDIR: '</text>Lib\\site-packages\\FreeTAKServer\\certs\\FTS_CRL.json'
  FTS_FEDERATION_KEYPASS: 'defaultpass'
  FTS_CLIENT_CERT_PASSWORD: 'supersecret'
  FTS_WEBSOCKET_KEY: 'YourWebsocketKey'